#!/usr/bin/env python3
"""Provision one worker locally + write services/orchestrator/.env.prod.

Sprint 24: the hosted-orchestrator CVM can't docker-in-docker provision
its own first worker.  Run this on the laptop instead:

  $ python3 scripts/seed-cvm-orchestrator-env.py

It calls WorkerPool.provision() (same path the orchestrator would have
used), captures the resulting team_id + identity_b64, then writes a
.env.prod file with TEAM_ID + WORKER_IDENTITY_B64 + TALLY_API_TOKEN +
REDPILL_API_KEY ready for `phala deploy -c docker-compose.yml -e .env.prod`.

Re-runs are safe — each call provisions a brand-new CVM.  Pre-existing
workers from a prior provision are not retired automatically (use
`phala cvms delete <id>` if you want to clean them up).
"""
from __future__ import annotations

import os
import secrets
import sys
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
ORCHESTRATOR_PKG = REPO_ROOT / "services" / "orchestrator"
ENV_OUT_PATH = ORCHESTRATOR_PKG / ".env.prod"


def _load_scripts_env() -> dict[str, str]:
    env_path = REPO_ROOT / "scripts" / ".env"
    if not env_path.exists():
        raise SystemExit(f"missing {env_path} — needs PHALA_CLOUD_API_KEY + REDPILL_API_KEY")
    out: dict[str, str] = {}
    for line in env_path.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        k, _, v = line.partition("=")
        out[k.strip()] = v.strip()
    return out


def main() -> None:
    sys.path.insert(0, str(ORCHESTRATOR_PKG))
    from tally_orchestrator.worker_pool import WorkerPool  # noqa: E402

    scripts_env = _load_scripts_env()
    pool = WorkerPool(scripts_env_path=str(REPO_ROOT / "scripts" / ".env"))

    print(">>> Provisioning a Phala CVM worker via the existing pool tooling...")
    print("    (takes ~3 minutes — laptop's local docker is doing the per-deploy build)")
    info = pool.provision()
    assert info.identity is not None
    print(f"    cvm_id   = {info.cvm_id}")
    print(f"    team_id  = {info.team_id}")
    print(f"    identity = {info.identity[:24]}...")

    # Preserve any existing .env.prod values (TALLY_API_TOKEN keeps the
    # client tokens valid across re-seeds; CF_TUNNEL_TOKEN from Sprint 24
    # is unrelated to the worker and must survive). Only TEAM_ID and
    # WORKER_IDENTITY_B64 get overwritten.
    existing: dict[str, str] = {}
    if ENV_OUT_PATH.exists():
        for line in ENV_OUT_PATH.read_text().splitlines():
            line = line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            k, _, v = line.partition("=")
            existing[k.strip()] = v.strip()

    tally_api_token = existing.get("TALLY_API_TOKEN") or scripts_env.get("TALLY_API_TOKEN") \
        or secrets.token_urlsafe(32)
    redpill_api_key = existing.get("REDPILL_API_KEY") or scripts_env.get("REDPILL_API_KEY", "")
    redpill_base = existing.get("REDPILL_BASE_URL") or scripts_env.get(
        "REDPILL_BASE_URL", "https://api.redpill.ai/v1"
    )
    cf_tunnel_token = existing.get("CF_TUNNEL_TOKEN", "")

    lines = [
        "# Generated by scripts/seed-cvm-orchestrator-env.py — Sprint 24 (worker pin)",
        "# + Sprint 26 (preserves prior CF_TUNNEL_TOKEN / TALLY_API_TOKEN on re-seed).",
        f"TEAM_ID={info.team_id}",
        f"WORKER_IDENTITY_B64={info.identity}",
        "",
        f"TALLY_API_TOKEN={tally_api_token}",
        f"REDPILL_API_KEY={redpill_api_key}",
        f"REDPILL_BASE_URL={redpill_base}",
        "",
        "TALLY_POOL_SIZE=1",
        "TALLY_SERIAL_PROVISION=true",
        "TALLY_RECOVERY_TIMEOUT=600",
    ]
    if cf_tunnel_token:
        lines += ["", f"CF_TUNNEL_TOKEN={cf_tunnel_token}"]
    ENV_OUT_PATH.write_text("\n".join(lines) + "\n")
    os.chmod(ENV_OUT_PATH, 0o600)
    print(f">>> Wrote {ENV_OUT_PATH} (mode 600).")
    print()
    print("Next:")
    print(f"    cd {ORCHESTRATOR_PKG}")
    print("    phala deploy -c docker-compose.yml -e .env.prod --name tally-orch-prod")


if __name__ == "__main__":
    main()
