#!/usr/bin/env python3
"""Provision one worker locally + write services/orchestrator/.env.prod.

Sprint 24: the hosted-orchestrator CVM can't docker-in-docker provision
its own first worker.  Run this on the laptop instead:

  $ python3 scripts/seed-cvm-orchestrator-env.py

It calls WorkerPool.provision() (same path the orchestrator would have
used), captures the resulting team_id + identity_b64, then writes a
.env.prod file with TEAM_ID + WORKER_IDENTITY_B64 + TALLY_API_TOKEN +
REDPILL_API_KEY ready for `phala deploy -c docker-compose.yml -e .env.prod`.

Re-runs are safe — each call provisions a brand-new CVM.  Pre-existing
workers from a prior provision are not retired automatically (use
`phala cvms delete <id>` if you want to clean them up).
"""
from __future__ import annotations

import os
import secrets
import sys
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
ORCHESTRATOR_PKG = REPO_ROOT / "services" / "orchestrator"
ENV_OUT_PATH = ORCHESTRATOR_PKG / ".env.prod"


def _load_scripts_env() -> dict[str, str]:
    env_path = REPO_ROOT / "scripts" / ".env"
    if not env_path.exists():
        raise SystemExit(f"missing {env_path} — needs PHALA_CLOUD_API_KEY + REDPILL_API_KEY")
    out: dict[str, str] = {}
    for line in env_path.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        k, _, v = line.partition("=")
        out[k.strip()] = v.strip()
    return out


def main() -> None:
    sys.path.insert(0, str(ORCHESTRATOR_PKG))
    from tally_orchestrator.worker_pool import WorkerPool  # noqa: E402

    scripts_env = _load_scripts_env()
    pool = WorkerPool(scripts_env_path=str(REPO_ROOT / "scripts" / ".env"))

    print(">>> Provisioning a Phala CVM worker via the existing pool tooling...")
    print("    (takes ~3 minutes — laptop's local docker is doing the per-deploy build)")
    info = pool.provision()
    assert info.identity is not None
    print(f"    cvm_id   = {info.cvm_id}")
    print(f"    team_id  = {info.team_id}")
    print(f"    identity = {info.identity[:24]}...")

    # Preserve EVERY key already in .env.prod that we don't replace.  The
    # original Sprint 26 version only explicitly preserved 4 keys, which
    # silently wiped Clerk + Stripe + credentials secrets on re-seed and
    # took production down with a 503 "Clerk not configured" cascade.
    # New rule: read the whole existing .env.prod into a dict, write the
    # known-managed keys first (TEAM_ID / WORKER_IDENTITY_B64 / TALLY_*
    # defaults), then append every other key as-is.
    existing: dict[str, str] = {}
    if ENV_OUT_PATH.exists():
        for line in ENV_OUT_PATH.read_text().splitlines():
            line = line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            k, _, v = line.partition("=")
            existing[k.strip()] = v.strip()

    tally_api_token = existing.get("TALLY_API_TOKEN") or scripts_env.get("TALLY_API_TOKEN") \
        or secrets.token_urlsafe(32)
    redpill_api_key = existing.get("REDPILL_API_KEY") or scripts_env.get("REDPILL_API_KEY", "")
    redpill_base = existing.get("REDPILL_BASE_URL") or scripts_env.get(
        "REDPILL_BASE_URL", "https://api.redpill.ai/v1"
    )

    # Keys this script manages directly — every other existing key gets
    # passed through verbatim so we don't accidentally wipe operator-set
    # secrets (Clerk, Stripe, credentials, custom env).
    managed_keys = {
        "TEAM_ID",
        "WORKER_IDENTITY_B64",
        "TALLY_API_TOKEN",
        "REDPILL_API_KEY",
        "REDPILL_BASE_URL",
        "TALLY_POOL_SIZE",
        "TALLY_SERIAL_PROVISION",
        "TALLY_RECOVERY_TIMEOUT",
    }
    lines = [
        "# Generated by scripts/seed-cvm-orchestrator-env.py — Sprint 24 (worker pin)",
        "# + Sprint 26 (preserves prior CF_TUNNEL_TOKEN / TALLY_API_TOKEN on re-seed).",
        "# + Sprint 54 (preserves ALL other operator-set keys — Clerk, Stripe, etc.).",
        f"TEAM_ID={info.team_id}",
        f"WORKER_IDENTITY_B64={info.identity}",
        "",
        f"TALLY_API_TOKEN={tally_api_token}",
        f"REDPILL_API_KEY={redpill_api_key}",
        f"REDPILL_BASE_URL={redpill_base}",
        "",
        "TALLY_POOL_SIZE=1",
        "TALLY_SERIAL_PROVISION=true",
        "TALLY_RECOVERY_TIMEOUT=600",
    ]
    # Pass-through: every other key the operator had configured (Clerk
    # publishable + secret, Stripe, credentials, ops channel, anything
    # else they set).  Preserves insertion order from the original file.
    passthrough = [(k, v) for k, v in existing.items() if k not in managed_keys]
    if passthrough:
        lines += ["", "# Preserved from prior .env.prod (operator-set):"]
        for k, v in passthrough:
            lines.append(f"{k}={v}")

    # Safety check (PR #8 review feedback): detect any key in the prior
    # .env.prod that would NOT appear in the new write.  In the current
    # logic, every non-managed key flows through passthrough, so the
    # diff should always be empty — but a future refactor could
    # regress, and that regression would silently take down prod (as
    # the original Sprint 26 version did).  Refuse to write unless
    # --force is passed, so the operator sees the drop in their
    # terminal before they redeploy.
    all_writes = managed_keys | {k for k, _ in passthrough}
    dropped = set(existing.keys()) - all_writes
    if dropped and "--force" not in sys.argv:
        raise SystemExit(
            f"refusing to drop {sorted(dropped)} from {ENV_OUT_PATH}. "
            f"re-run with --force to confirm, or fix the seed script "
            f"to add these keys to managed_keys / passthrough."
        )

    ENV_OUT_PATH.write_text("\n".join(lines) + "\n")
    os.chmod(ENV_OUT_PATH, 0o600)
    print(f">>> Wrote {ENV_OUT_PATH} (mode 600).")
    print()
    print("Next:")
    print(f"    cd {ORCHESTRATOR_PKG}")
    print("    phala deploy -c docker-compose.yml -e .env.prod --name tally-orch-prod")


if __name__ == "__main__":
    main()
